In [1]:
import pandas as pd
import seaborn as sns

In [15]:
df = pd.read_excel("data/demo3.xlsx")
df = df.dropna()

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
df

,Unnamed: 0,DATE_TIME,CB_FLOW,CB_PRESS,CB_TEMP,STEAM_FLOW,STEAM_TEMP,STEAM_PRESS,O2_PRESS,O2_FLOW,...,TOP_PRESS_1,CO,CO2,H2,SKIN_TEMP_AVG,CO/CO2,Next_1hr,Next_2hr,Next_3hr,Next_4hr
0,5,2021-01-07 01:00:00,312520,3.20,126,4,189,3.39,3.25,7916,...,2,22.30,21.10,4.12,72.222703,1.056872,1.066888,1.040300,1.058101,1.070583
1,10,2021-01-07 02:00:00,311177,3.21,126,4,191,3.40,3.26,7922,...,1,22.49,21.08,4.11,77.342288,1.066888,1.040300,1.058101,1.070583,1.063537
2,16,2021-01-07 03:00:00,301825,3.17,127,4,190,3.36,3.21,7914,...,1,22.20,21.34,4.12,82.636160,1.040300,1.058101,1.070583,1.063537,1.072546
3,22,2021-01-07 04:00:00,313514,3.27,124,6,192,3.48,3.32,8411,...,2,22.40,21.17,4.14,84.636354,1.058101,1.070583,1.063537,1.072546,1.043499
4,28,2021-01-07 05:00:00,318428,3.21,127,6,189,3.43,3.27,8096,...,1,22.60,21.11,3.88,83.540342,1.070583,1.063537,1.072546,1.043499,1.041431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3570,25351,2021-12-31 15:00:00,283309,2.77,78,2,192,2.94,2.81,2881,...,1,22.33,20.10,2.96,80.174008,1.110945,1.102172,1.094100,1.099510,1.114258
3571,25357,2021-12-31 16:00:00,282397,2.83,77,3,190,3.00,2.87,2917,...,1,22.33,20.26,3.15,79.477945,1.102172,1.094100,1.099510,1.114258,1.123274
3572,25363,2021-12-31 17:00:00,277292,2.78,77,4,190,2.97,2.82,2913,...,1,22.44,20.51,3.22,78.676326,1.094100,1.099510,1.114258,1.123274,1.102804
3573,25369,2021-12-31 18:00:00,289341,2.78,76,5,191,2.98,2.82,2900,...,1,22.43,20.40,3.30,74.029351,1.099510,1.114258,1.123274,1.102804,1.105160
3574,25375,2021-12-31 19:00:00,278463,2.74,76,5,190,2.93,2.78,2901,...,1,22.82,20.48,3.40,72.821213,1.114258,1.123274,1.102804,1.105160,1.092583

In [25]:
# predicting first hour
df1 = df.drop(columns = ["Unnamed: 0","CO/CO2","CO","CO2","SKIN_TEMP_AVG"])
df1

,DATE_TIME,CB_FLOW,CB_PRESS,CB_TEMP,STEAM_FLOW,STEAM_TEMP,STEAM_PRESS,O2_PRESS,O2_FLOW,O2_PER,...,TOP_TEMP3,TOP_TEMP4,TOP_SPRAY,TOP_TEMP,TOP_PRESS_1,H2,Next_1hr,Next_2hr,Next_3hr,Next_4hr
0,2021-01-07 01:00:00,312520,3.20,126,4,189,3.39,3.25,7916,23.08,...,117,132,0.0,128,2,4.12,1.066888,1.040300,1.058101,1.070583
1,2021-01-07 02:00:00,311177,3.21,126,4,191,3.40,3.26,7922,23.08,...,126,129,0.0,128,1,4.11,1.040300,1.058101,1.070583,1.063537
2,2021-01-07 03:00:00,301825,3.17,127,4,190,3.36,3.21,7914,23.08,...,150,139,0.0,144,1,4.12,1.058101,1.070583,1.063537,1.072546
3,2021-01-07 04:00:00,313514,3.27,124,6,192,3.48,3.32,8411,23.08,...,149,133,0.0,141,2,4.14,1.070583,1.063537,1.072546,1.043499
4,2021-01-07 05:00:00,318428,3.21,127,6,189,3.43,3.27,8096,23.08,...,124,140,0.0,136,1,3.88,1.063537,1.072546,1.043499,1.041431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3570,2021-12-31 15:00:00,283309,2.77,78,2,192,2.94,2.81,2881,22.26,...,106,119,0.1,118,1,2.96,1.102172,1.094100,1.099510,1.114258
3571,2021-12-31 16:00:00,282397,2.83,77,3,190,3.00,2.87,2917,22.28,...,138,139,0.1,140,1,3.15,1.094100,1.099510,1.114258,1.123274
3572,2021-12-31 17:00:00,277292,2.78,77,4,190,2.97,2.82,2913,22.32,...,139,146,0.1,144,1,3.22,1.099510,1.114258,1.123274,1.102804
3573,2021-12-31 18:00:00,289341,2.78,76,5,191,2.98,2.82,2900,22.31,...,109,120,0.1,118,1,3.30,1.114258,1.123274,1.102804,1.105160
3574,2021-12-31 19:00:00,278463,2.74,76,5,190,2.93,2.78,2901,22.33,...,127,126,0.1,127,1,3.40,1.123274,1.102804,1.105160,1.092583

In [31]:
df11 = df1.drop(columns = ["Next_2hr","Next_3hr","Next_4hr","DATE_TIME"])
df11

,CB_FLOW,CB_PRESS,CB_TEMP,STEAM_FLOW,STEAM_TEMP,STEAM_PRESS,O2_PRESS,O2_FLOW,O2_PER,PCI,...,TOP_PRESS,TOP_TEMP1,TOP_TEMP2,TOP_TEMP3,TOP_TEMP4,TOP_SPRAY,TOP_TEMP,TOP_PRESS_1,H2,Next_1hr
0,312520,3.20,126,4,189,3.39,3.25,7916,23.08,36,...,1.50,123,139,117,132,0.0,128,2,4.12,1.066888
1,311177,3.21,126,4,191,3.40,3.26,7922,23.08,33,...,1.50,117,138,126,129,0.0,128,1,4.11,1.040300
2,301825,3.17,127,4,190,3.36,3.21,7914,23.08,30,...,1.49,132,155,150,139,0.0,144,1,4.12,1.058101
3,313514,3.27,124,6,192,3.48,3.32,8411,23.08,30,...,1.50,130,151,149,133,0.0,141,2,4.14,1.070583
4,318428,3.21,127,6,189,3.43,3.27,8096,23.08,27,...,1.49,137,145,124,140,0.0,136,1,3.88,1.063537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3570,283309,2.77,78,2,192,2.94,2.81,2881,22.26,11,...,1.09,122,127,106,119,0.1,118,1,2.96,1.102172
3571,282397,2.83,77,3,190,3.00,2.87,2917,22.28,12,...,1.09,131,150,138,139,0.1,140,1,3.15,1.094100
3572,277292,2.78,77,4,190,2.97,2.82,2913,22.32,8,...,1.09,137,154,139,146,0.1,144,1,3.22,1.099510
3573,289341,2.78,76,5,191,2.98,2.82,2900,22.31,9,...,1.09,115,129,109,120,0.1,118,1,3.30,1.114258
3574,278463,2.74,76,5,190,2.93,2.78,2901,22.33,12,...,1.09,124,133,127,126,0.1,127,1,3.40,1.123274

In [32]:
from sklearn.model_selection import train_test_split
X = df11.drop(columns = ["Next_1hr"])
y = df11["Next_1hr"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
model_for_1hr = LinearRegression()
model_for_1hr.fit(X_train, y_train)
model_for_1hr.score(X_test, y_test)

0.6774962436972156

In [35]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error, mean_squared_log_error, mean_poisson_deviance, mean_gamma_deviance

y_pred = model_for_1hr.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print(mean_poisson_deviance(y_test, y_pred))
print("mge",mean_gamma_deviance(y_test, y_pred))

mse 0.0093871177819525
0.6774962436972156
mae 0.04954806965088485
mape 0.04142637209594146
msle 0.0011539789979324964
0.005235070056801988
mge 0.003590614900683834

In [36]:
from sklearn.tree import DecisionTreeRegressor

In [37]:
model_for_1hr_dtree = DecisionTreeRegressor()
model_for_1hr_dtree.fit(X_train, y_train)
model_for_1hr_dtree.score(X_test, y_test)

0.7619065961578246

In [40]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error, mean_squared_log_error, mean_poisson_deviance, mean_gamma_deviance, accuracy_score

y_pred = model_for_1hr_dtree.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))
# print("accuracy",accuracy_score(y_test, y_pred))

mse 0.00693018540495426
r2 0.7619065961578246
mae 0.04462108684136287
mape 0.03771549399233872
msle 0.0010231029212783359
mpd 0.004417689455617985
mgd 0.0033261037654790733

In [44]:
from sklearn.neighbors import KNeighborsRegressor

In [45]:
model_for_1hr_knn = KNeighborsRegressor()
model_for_1hr_knn.fit(X_train, y_train)

y_pred = model_for_1hr_knn.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))

mse 0.021738740676600664
r2 0.253143969390186
mae 0.05690229559209409
mape 0.045367499552564014
msle 0.002482874604990274
mpd 0.012178901203812922
mgd 0.007739185298723462

In [46]:
from sklearn.linear_model import LogisticRegression

In [48]:
from sklearn.ensemble import RandomForestRegressor

model_for_1hr_rf = RandomForestRegressor()
model_for_1hr_rf.fit(X_train, y_train)

y_pred = model_for_1hr_rf.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))

mse 0.006486520369250554
r2 0.7771491491840309
mae 0.033194663636678695
mape 0.02716450270649437
msle 0.0006949265922264838
mpd 0.003248591354233152
mgd 0.0020660016268721024

In [49]:
from sklearn.ensemble import BaggingRegressor

model_for_1hr_bag = BaggingRegressor()
model_for_1hr_bag.fit(X_train, y_train)

y_pred = model_for_1hr_bag.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))

mse 0.007903068251046435
r2 0.7284822395453514
mae 0.03579049916247615
mape 0.029201407791138705
msle 0.0008213360902246729
mpd 0.0039006399968435175
mgd 0.0024230143052343276

In [50]:
from sklearn.ensemble import AdaBoostRegressor

model_for_1hr_ada = AdaBoostRegressor()
model_for_1hr_ada.fit(X_train, y_train)

y_pred = model_for_1hr_ada.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))

mse 0.0067328276491724365
r2 0.7686870179074585
mae 0.05181405438936302
mape 0.04462744760654463
msle 0.0010057940900857463
mpd 0.0043281225894382935
mgd 0.003302248341853543

In [51]:
from sklearn.ensemble import GradientBoostingRegressor

model_for_1hr_gb = GradientBoostingRegressor()
model_for_1hr_gb.fit(X_train, y_train)

y_pred = model_for_1hr_gb.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))

mse 0.005838772946402211
r2 0.7994031553504037
mae 0.037929771122031816
mape 0.03141264574624897
msle 0.0007313243578170489
mpd 0.0032670911973132627
mgd 0.0022594443600894736

In [53]:
import xgboost as xgb

model_for_1hr_xgb = xgb.XGBRegressor()
model_for_1hr_xgb.fit(X_train, y_train)

y_pred = model_for_1hr_xgb.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))

mse 0.006256118145914032
r2 0.7850648464419687
mae 0.03366201332456448
mape 0.02769427879949473
msle 0.0006580206939895542
mpd 0.003088401891463862
mgd 0.0019487190859422696

In [56]:
df1

,DATE_TIME,CB_FLOW,CB_PRESS,CB_TEMP,STEAM_FLOW,STEAM_TEMP,STEAM_PRESS,O2_PRESS,O2_FLOW,O2_PER,...,TOP_TEMP3,TOP_TEMP4,TOP_SPRAY,TOP_TEMP,TOP_PRESS_1,H2,Next_1hr,Next_2hr,Next_3hr,Next_4hr
0,2021-01-07 01:00:00,312520,3.20,126,4,189,3.39,3.25,7916,23.08,...,117,132,0.0,128,2,4.12,1.066888,1.040300,1.058101,1.070583
1,2021-01-07 02:00:00,311177,3.21,126,4,191,3.40,3.26,7922,23.08,...,126,129,0.0,128,1,4.11,1.040300,1.058101,1.070583,1.063537
2,2021-01-07 03:00:00,301825,3.17,127,4,190,3.36,3.21,7914,23.08,...,150,139,0.0,144,1,4.12,1.058101,1.070583,1.063537,1.072546
3,2021-01-07 04:00:00,313514,3.27,124,6,192,3.48,3.32,8411,23.08,...,149,133,0.0,141,2,4.14,1.070583,1.063537,1.072546,1.043499
4,2021-01-07 05:00:00,318428,3.21,127,6,189,3.43,3.27,8096,23.08,...,124,140,0.0,136,1,3.88,1.063537,1.072546,1.043499,1.041431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3570,2021-12-31 15:00:00,283309,2.77,78,2,192,2.94,2.81,2881,22.26,...,106,119,0.1,118,1,2.96,1.102172,1.094100,1.099510,1.114258
3571,2021-12-31 16:00:00,282397,2.83,77,3,190,3.00,2.87,2917,22.28,...,138,139,0.1,140,1,3.15,1.094100,1.099510,1.114258,1.123274
3572,2021-12-31 17:00:00,277292,2.78,77,4,190,2.97,2.82,2913,22.32,...,139,146,0.1,144,1,3.22,1.099510,1.114258,1.123274,1.102804
3573,2021-12-31 18:00:00,289341,2.78,76,5,191,2.98,2.82,2900,22.31,...,109,120,0.1,118,1,3.30,1.114258,1.123274,1.102804,1.105160
3574,2021-12-31 19:00:00,278463,2.74,76,5,190,2.93,2.78,2901,22.33,...,127,126,0.1,127,1,3.40,1.123274,1.102804,1.105160,1.092583

In [58]:
df12 = df1.drop(columns = ["Next_3hr","Next_4hr","DATE_TIME"])
df12

,CB_FLOW,CB_PRESS,CB_TEMP,STEAM_FLOW,STEAM_TEMP,STEAM_PRESS,O2_PRESS,O2_FLOW,O2_PER,PCI,...,TOP_TEMP1,TOP_TEMP2,TOP_TEMP3,TOP_TEMP4,TOP_SPRAY,TOP_TEMP,TOP_PRESS_1,H2,Next_1hr,Next_2hr
0,312520,3.20,126,4,189,3.39,3.25,7916,23.08,36,...,123,139,117,132,0.0,128,2,4.12,1.066888,1.040300
1,311177,3.21,126,4,191,3.40,3.26,7922,23.08,33,...,117,138,126,129,0.0,128,1,4.11,1.040300,1.058101
2,301825,3.17,127,4,190,3.36,3.21,7914,23.08,30,...,132,155,150,139,0.0,144,1,4.12,1.058101,1.070583
3,313514,3.27,124,6,192,3.48,3.32,8411,23.08,30,...,130,151,149,133,0.0,141,2,4.14,1.070583,1.063537
4,318428,3.21,127,6,189,3.43,3.27,8096,23.08,27,...,137,145,124,140,0.0,136,1,3.88,1.063537,1.072546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3570,283309,2.77,78,2,192,2.94,2.81,2881,22.26,11,...,122,127,106,119,0.1,118,1,2.96,1.102172,1.094100
3571,282397,2.83,77,3,190,3.00,2.87,2917,22.28,12,...,131,150,138,139,0.1,140,1,3.15,1.094100,1.099510
3572,277292,2.78,77,4,190,2.97,2.82,2913,22.32,8,...,137,154,139,146,0.1,144,1,3.22,1.099510,1.114258
3573,289341,2.78,76,5,191,2.98,2.82,2900,22.31,9,...,115,129,109,120,0.1,118,1,3.30,1.114258,1.123274
3574,278463,2.74,76,5,190,2.93,2.78,2901,22.33,12,...,124,133,127,126,0.1,127,1,3.40,1.123274,1.102804

In [59]:
X = df12.drop(columns = ["Next_2hr"])
y = df12["Next_2hr"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model_for_2hr = GradientBoostingRegressor()
model_for_2hr.fit(X_train, y_train)

y_pred = model_for_2hr.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))

mse 0.0016955818784288557
r2 0.9406006195799361
mae 0.022481300114386923
mape 0.018751880888653583
msle 0.00025536470445218767
mpd 0.0011031760975704027
mgd 0.0007917285820029725

In [60]:
df13 = df1.drop(columns = ["Next_4hr","DATE_TIME"])
df13

,CB_FLOW,CB_PRESS,CB_TEMP,STEAM_FLOW,STEAM_TEMP,STEAM_PRESS,O2_PRESS,O2_FLOW,O2_PER,PCI,...,TOP_TEMP2,TOP_TEMP3,TOP_TEMP4,TOP_SPRAY,TOP_TEMP,TOP_PRESS_1,H2,Next_1hr,Next_2hr,Next_3hr
0,312520,3.20,126,4,189,3.39,3.25,7916,23.08,36,...,139,117,132,0.0,128,2,4.12,1.066888,1.040300,1.058101
1,311177,3.21,126,4,191,3.40,3.26,7922,23.08,33,...,138,126,129,0.0,128,1,4.11,1.040300,1.058101,1.070583
2,301825,3.17,127,4,190,3.36,3.21,7914,23.08,30,...,155,150,139,0.0,144,1,4.12,1.058101,1.070583,1.063537
3,313514,3.27,124,6,192,3.48,3.32,8411,23.08,30,...,151,149,133,0.0,141,2,4.14,1.070583,1.063537,1.072546
4,318428,3.21,127,6,189,3.43,3.27,8096,23.08,27,...,145,124,140,0.0,136,1,3.88,1.063537,1.072546,1.043499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3570,283309,2.77,78,2,192,2.94,2.81,2881,22.26,11,...,127,106,119,0.1,118,1,2.96,1.102172,1.094100,1.099510
3571,282397,2.83,77,3,190,3.00,2.87,2917,22.28,12,...,150,138,139,0.1,140,1,3.15,1.094100,1.099510,1.114258
3572,277292,2.78,77,4,190,2.97,2.82,2913,22.32,8,...,154,139,146,0.1,144,1,3.22,1.099510,1.114258,1.123274
3573,289341,2.78,76,5,191,2.98,2.82,2900,22.31,9,...,129,109,120,0.1,118,1,3.30,1.114258,1.123274,1.102804
3574,278463,2.74,76,5,190,2.93,2.78,2901,22.33,12,...,133,127,126,0.1,127,1,3.40,1.123274,1.102804,1.105160

In [66]:
X = df13.drop(columns = ["Next_3hr"])
y = df13["Next_3hr"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model_for_3hr = xgb.XGBRegressor()
model_for_3hr.fit(X_train, y_train)

y_pred = model_for_3hr.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))

mse 0.0059667829994847115
r2 0.8591297051570137
mae 0.028567872903630845
mape 0.022289088497038104
msle 0.0004942240965036439
mpd 0.002441796122885797
mgd 0.001323449291449044

In [62]:
df14 = df1.drop(columns = ["DATE_TIME"])
df14

,CB_FLOW,CB_PRESS,CB_TEMP,STEAM_FLOW,STEAM_TEMP,STEAM_PRESS,O2_PRESS,O2_FLOW,O2_PER,PCI,...,TOP_TEMP3,TOP_TEMP4,TOP_SPRAY,TOP_TEMP,TOP_PRESS_1,H2,Next_1hr,Next_2hr,Next_3hr,Next_4hr
0,312520,3.20,126,4,189,3.39,3.25,7916,23.08,36,...,117,132,0.0,128,2,4.12,1.066888,1.040300,1.058101,1.070583
1,311177,3.21,126,4,191,3.40,3.26,7922,23.08,33,...,126,129,0.0,128,1,4.11,1.040300,1.058101,1.070583,1.063537
2,301825,3.17,127,4,190,3.36,3.21,7914,23.08,30,...,150,139,0.0,144,1,4.12,1.058101,1.070583,1.063537,1.072546
3,313514,3.27,124,6,192,3.48,3.32,8411,23.08,30,...,149,133,0.0,141,2,4.14,1.070583,1.063537,1.072546,1.043499
4,318428,3.21,127,6,189,3.43,3.27,8096,23.08,27,...,124,140,0.0,136,1,3.88,1.063537,1.072546,1.043499,1.041431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3570,283309,2.77,78,2,192,2.94,2.81,2881,22.26,11,...,106,119,0.1,118,1,2.96,1.102172,1.094100,1.099510,1.114258
3571,282397,2.83,77,3,190,3.00,2.87,2917,22.28,12,...,138,139,0.1,140,1,3.15,1.094100,1.099510,1.114258,1.123274
3572,277292,2.78,77,4,190,2.97,2.82,2913,22.32,8,...,139,146,0.1,144,1,3.22,1.099510,1.114258,1.123274,1.102804
3573,289341,2.78,76,5,191,2.98,2.82,2900,22.31,9,...,109,120,0.1,118,1,3.30,1.114258,1.123274,1.102804,1.105160
3574,278463,2.74,76,5,190,2.93,2.78,2901,22.33,12,...,127,126,0.1,127,1,3.40,1.123274,1.102804,1.105160,1.092583

In [65]:
X = df14.drop(columns = ["Next_4hr"])
y = df14["Next_4hr"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model_for_4hr = xgb.XGBRegressor()


model_for_4hr.fit(X_train, y_train)

y_pred = model_for_4hr.predict(X_test)
print("mse",mean_squared_error(y_test, y_pred))
print("r2",r2_score(y_test, y_pred))
print("mae",mean_absolute_error(y_test, y_pred))
print("mape",mean_absolute_percentage_error(y_test, y_pred))
print("msle",mean_squared_log_error(y_test, y_pred))
print("mpd",mean_poisson_deviance(y_test, y_pred))
print("mgd",mean_gamma_deviance(y_test, y_pred))

mse 0.006813869250895521
r2 0.7723943431690317
mae 0.030352235064886005
mape 0.02394341908368742
msle 0.0006278073069358212
mpd 0.002963607955610452
mgd 0.001611681923139979